from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Callable

import json
import numpy as np

from src.calibration.phase_gain_calibration import (
    PhaseGainCalibrationResult,
    calibrate_phase_gain_from_blocks,
)
from src.core import now_iso


CollectPhaseGainBlocksFn = Callable[[float, int], list[np.ndarray]]


@dataclass
class GainPhaseGainCalibrationResult:
    """
    단일 gain에서 측정한 phase/gain calibration 결과.
    """

    gain: float
    result: PhaseGainCalibrationResult

    def to_dict(self) -> dict[str, Any]:
        data = self.result.to_dict()
        data["gain"] = float(self.gain)
        return data


@dataclass
class GainPhaseGainCalibrationSet:
    """
    여러 gain에서 측정한 phase/gain calibration 결과 묶음.

    CLI / OpenCV viewer / GUI viewer에서 공통으로 로드해서 사용한다.
    """

    mode: str
    created_at: str
    gain_list: list[float]
    num_gains: int
    num_blocks_per_gain: int
    sample_rate: float | None
    center_freq: float | None
    ref_channel: int
    target_channel: int
    profiles: dict[str, dict[str, Any]]
    note: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def save_json(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with path.open("w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)

        return path

    def get_profile(self, gain: int | float) -> dict[str, Any]:
        return get_phase_gain_profile_for_gain(self, gain)


def gain_to_key(gain: int | float) -> str:
    gain_value = float(gain)
    if gain_value.is_integer():
        return str(int(gain_value))
    return str(gain_value)


def _profile_key_to_float(key: str) -> float:
    try:
        return float(key)
    except ValueError as exc:
        raise ValueError(f"Invalid gain profile key: {key}") from exc


def _validate_gain_list(gain_list: list[int | float]) -> list[float]:
    if not gain_list:
        raise ValueError("gain_list must not be empty")

    gains = [float(gain) for gain in gain_list]
    return sorted(dict.fromkeys(gains))


def calibrate_phase_gain_by_gain(
    gain_list: list[int | float],
    collect_fn: CollectPhaseGainBlocksFn,
    *,
    num_blocks_per_gain: int = 200,
    ref_channel: int = 0,
    target_channel: int = 1,
    sample_rate: float | None = None,
    center_freq: float | None = None,
) -> GainPhaseGainCalibrationSet:
    """
    gain별 phase/gain calibration을 수행한다.

    collect_fn:
        collect_fn(gain, num_blocks) -> list[np.ndarray]

    설계 의도:
    - 기존 calibrate_phase_gain_from_blocks()는 수정하지 않는다.
    - gain 20/25/30/35/40에서 각각 calibration을 수행한다.
    - 하나의 phase_gain_by_gain_latest.json으로 저장한다.
    """
    gains = _validate_gain_list(gain_list)
    profiles: dict[str, dict[str, Any]] = {}

    print("=" * 60)
    print("GAIN-WISE PHASE/GAIN CALIBRATION 시작")
    print("=" * 60)
    print(f"gain_list           : {gains}")
    print(f"num_blocks_per_gain : {num_blocks_per_gain}")
    print(f"ref_channel         : {ref_channel}")
    print(f"target_channel      : {target_channel}")
    print("=" * 60)

    for gain in gains:
        print(f"\n[gain={gain:g}] phase/gain calibration block 수집 중...")
        blocks = collect_fn(gain, int(num_blocks_per_gain))

        result = calibrate_phase_gain_from_blocks(
            blocks,
            ref_channel=int(ref_channel),
            target_channel=int(target_channel),
            sample_rate=sample_rate,
            center_freq=center_freq,
        )

        profile = GainPhaseGainCalibrationResult(
            gain=gain,
            result=result,
        )

        profile_dict = profile.to_dict()
        profiles[gain_to_key(gain)] = profile_dict

        print(
            f"  gain={gain:g} | "
            f"gain_corr={result.gain_correction_mean:.10g} | "
            f"phase={result.phase_offset_deg_mean:.6f} deg | "
            f"coh_like={result.coherence_like_mean:.10g}"
        )

    return GainPhaseGainCalibrationSet(
        mode="GAIN_PHASE_GAIN_CALIBRATION",
        created_at=now_iso(),
        gain_list=gains,
        num_gains=len(gains),
        num_blocks_per_gain=int(num_blocks_per_gain),
        sample_rate=sample_rate,
        center_freq=center_freq,
        ref_channel=int(ref_channel),
        target_channel=int(target_channel),
        profiles=profiles,
        note=(
            "Gain-wise phase/gain calibration profile set. "
            "Each gain profile is generated by existing calibrate_phase_gain_from_blocks(). "
            "Use get_phase_gain_profile_for_gain() from CLI / OpenCV viewer / GUI viewer."
        ),
    )


def load_phase_gain_by_gain_calibration(
    path: str | Path,
) -> GainPhaseGainCalibrationSet:
    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if data.get("mode") != "GAIN_PHASE_GAIN_CALIBRATION":
        raise ValueError(
            "Invalid gain phase/gain calibration file: "
            f"mode={data.get('mode')!r}"
        )

    if "profiles" not in data or not isinstance(data["profiles"], dict):
        raise ValueError("Invalid gain phase/gain calibration file: missing profiles")

    return GainPhaseGainCalibrationSet(
        mode=str(data["mode"]),
        created_at=str(data.get("created_at", "")),
        gain_list=[float(x) for x in data.get("gain_list", [])],
        num_gains=int(data.get("num_gains", len(data["profiles"]))),
        num_blocks_per_gain=int(data.get("num_blocks_per_gain", 0)),
        sample_rate=_optional_float(data.get("sample_rate")),
        center_freq=_optional_float(data.get("center_freq")),
        ref_channel=int(data.get("ref_channel", 0)),
        target_channel=int(data.get("target_channel", 1)),
        profiles=data["profiles"],
        note=str(data.get("note", "")),
    )


def get_phase_gain_profile_for_gain(
    profile_set: GainPhaseGainCalibrationSet | dict[str, Any],
    gain: int | float,
    *,
    allow_nearest: bool = True,
) -> dict[str, Any]:
    profiles = (
        profile_set.profiles
        if isinstance(profile_set, GainPhaseGainCalibrationSet)
        else profile_set["profiles"]
    )

    key = gain_to_key(gain)
    if key in profiles:
        return dict(profiles[key])

    if not allow_nearest:
        available = ", ".join(sorted(profiles.keys(), key=_profile_key_to_float))
        raise KeyError(f"gain={gain} profile not found. Available gains: {available}")

    target = float(gain)
    nearest_key = min(
        profiles.keys(),
        key=lambda item: abs(_profile_key_to_float(item) - target),
    )

    profile = dict(profiles[nearest_key])
    profile["requested_gain"] = float(gain)
    profile["matched_gain"] = _profile_key_to_float(nearest_key)
    profile["matched_by"] = "nearest"
    return profile


def get_phase_gain_correction_for_gain(
    profile_set: GainPhaseGainCalibrationSet | dict[str, Any],
    gain: int | float,
    *,
    allow_nearest: bool = True,
) -> tuple[float, float]:
    """
    현재 gain에 맞는 RX1 gain correction과 phase offset rad를 반환한다.

    Returns:
        (gain_correction, phase_offset_rad)
    """
    profile = get_phase_gain_profile_for_gain(
        profile_set,
        gain,
        allow_nearest=allow_nearest,
    )

    gain_correction = float(profile["gain_correction_mean"])
    phase_offset_rad = float(profile["phase_offset_rad_mean"])

    return gain_correction, phase_offset_rad


def _optional_float(value: Any) -> float | None:
    if value is None:
        return None
    return float(value)